# Generated by Django 4.1.3 on 2022-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exercises', models.TextField()),
                ('day_exercises', models.DateField()),
                ('counts_exercises', models.IntegerField()),
                ('sets_exercises', models.IntegerField()),
                ('weight_exercises', models.FloatField()),
            ],
        ),
    ]
