# Generated by Django 4.1.3 on 2022-11-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='day_exercises',
            field=models.TextField(),
        ),
    ]
